/*
 * generated by Xtext
 */
package ch.vobos.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TypescriptUiModule extends ch.vobos.ui.AbstractTypescriptUiModule {
	public TypescriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
