/*
 * generated by Xtext
 */
package ch.vobos.ui.contentassist

import ch.vobos.ui.contentassist.AbstractTypescriptProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TypescriptProposalProvider extends AbstractTypescriptProposalProvider {
}
