/*
* generated by Xtext
*/
package ch.vobos;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TypescriptUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ch.vobos.ui.internal.TypescriptActivator.getInstance().getInjector("ch.vobos.Typescript");
	}
	
}
