/*
 * generated by Xtext
 */
package ch.vobos;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TypescriptRuntimeModule extends ch.vobos.AbstractTypescriptRuntimeModule {

}
